services:
  controlplane:
    image: prabodhtr/trino:trino-controlplane-1.0
    environment:
      ACTIVE_PROFILE: test
    env_file:
      - .env
    ports:
      - "9001:9001"
    volumes:
      - ./etc/controlplane:/etc/controlplane
    networks:
      - default

  trino_1:
    image: prabodhtr/trino:trino-server-v461-amd64
    environment:
      HTTP_PORT: 8080
      CLUSTER_HOST: trino_1
      NODE_ID: trino_1
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "7095:7095"
    volumes:
      - ./etc/trino:/etc/trino 
    depends_on:
      - postgres
    networks:
      - default
      - db_network
      
  trino_2:
    image: prabodhtr/trino:trino-server-v461-amd64
    environment:
      HTTP_PORT: 8090
      CLUSTER_HOST: trino_2
      NODE_ID: trino_2
    env_file:
      - .env
    ports:
      - "8090:8090"
    volumes:
      - ./etc/trino:/etc/trino 
    depends_on:
      - postgres
    networks:
      - default
      - db_network

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network
      
  envoy:
    image: prabodhtr/trino:trino-envoyproxy-1.0
    env_file: .env
    environment:
      ENVOY_UID: 777
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./etc/envoy:/etc/envoy
      - ./logs/envoy:/var/log
    networks:
      - default

volumes:
  postgres-data:

networks:
  db_network:
    driver: bridge
  
 
